[[ATK]]
arch = "aarch64"
git-tree-sha1 = "4b1ea4ce987f40e0887b34d4fdf7db75f30d7624"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "29db69c0f8eae9f84a0b689156490bea004ca606815cec215d67a1137806b7a8"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+4/ATK.v2.34.1.aarch64-linux-gnu.tar.gz"
[[ATK]]
arch = "aarch64"
git-tree-sha1 = "71e65d187155d72747d56e14f241bff53bc89662"
libc = "musl"
os = "linux"

    [[ATK.download]]
    sha256 = "cb36f04aeedf5b66dae0786454eecd68082d52e5f57c7e4736c3e9f2086ab57d"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+4/ATK.v2.34.1.aarch64-linux-musl.tar.gz"
[[ATK]]
arch = "armv7l"
git-tree-sha1 = "b9426dd032160815d442ca32e6d310f02689dbd2"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "33a017a5eda0eb2ec010f8349add38fbb6af869237f63f167a28c821c1f1e4ef"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+4/ATK.v2.34.1.armv7l-linux-gnueabihf.tar.gz"
[[ATK]]
arch = "armv7l"
git-tree-sha1 = "d8a7e86573948a5b09e1c46428b51ff0c9b707d7"
libc = "musl"
os = "linux"

    [[ATK.download]]
    sha256 = "2144d7de2058ad08c9ed8e809f892723b5f186e3a56b2c190430131a6e3622ee"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+4/ATK.v2.34.1.armv7l-linux-musleabihf.tar.gz"
[[ATK]]
arch = "i686"
git-tree-sha1 = "e22412ce91e7df9fc81abd8c2b3bf0b0fbecbdba"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "de38a40976741b19149d208293f1da4dac09129fd5b788cdc3c90bfdba6ab3b6"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+4/ATK.v2.34.1.i686-linux-gnu.tar.gz"
[[ATK]]
arch = "i686"
git-tree-sha1 = "7a0e4ee43efbe8cd5d5af01923ef46c138178f8e"
libc = "musl"
os = "linux"

    [[ATK.download]]
    sha256 = "4f9b335e9416abe37287bd3d843e45df5a28d79131992ad196e6f93abb3f0667"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+4/ATK.v2.34.1.i686-linux-musl.tar.gz"
[[ATK]]
arch = "i686"
git-tree-sha1 = "0c0d697f4aead0339dc6d2f03cabf37f4db7c84d"
os = "windows"

    [[ATK.download]]
    sha256 = "1a2f03a982b516fa96862fbd410cccafd34b08d25eace52a4c997c16ac32ff8f"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+4/ATK.v2.34.1.i686-w64-mingw32.tar.gz"
[[ATK]]
arch = "powerpc64le"
git-tree-sha1 = "a41cfaed7d28163be916f68211f21177913bb94e"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "0f1dc9361381cf4a91bbb9c5511c51613279831dc4531af3f07b8e49d0017309"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+4/ATK.v2.34.1.powerpc64le-linux-gnu.tar.gz"
[[ATK]]
arch = "x86_64"
git-tree-sha1 = "147aeb6320fd82916a2d2ecd08d398f1d8b9f17a"
os = "macos"

    [[ATK.download]]
    sha256 = "2154c82290b29eefea05baf30b7c4e1a2f651636d694ac26291f2295e29ea665"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+4/ATK.v2.34.1.x86_64-apple-darwin14.tar.gz"
[[ATK]]
arch = "x86_64"
git-tree-sha1 = "58da2fc43349d544585cda79c9aedea095f12fe7"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "875324a23b46953a4ca2797b87049e0a2595a055776eb7ce920f8afedd4270c2"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+4/ATK.v2.34.1.x86_64-linux-gnu.tar.gz"
[[ATK]]
arch = "x86_64"
git-tree-sha1 = "b6135df4d1d6b27a373ce1dbea121d639bb88d9e"
libc = "musl"
os = "linux"

    [[ATK.download]]
    sha256 = "f44bb0a89d31a4e47dd768b897f16b6da202f1bb6b448aa2455332f0cd99637e"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+4/ATK.v2.34.1.x86_64-linux-musl.tar.gz"
[[ATK]]
arch = "x86_64"
git-tree-sha1 = "d68df50a90a3b3563387da0b64c30947d915e193"
os = "freebsd"

    [[ATK.download]]
    sha256 = "077469cbef84e379732cb4384afb19a1c129e18cad778163e09d3783dce1bba2"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+4/ATK.v2.34.1.x86_64-unknown-freebsd11.1.tar.gz"
[[ATK]]
arch = "x86_64"
git-tree-sha1 = "e724c430e2eb6f50b71beefbf2f6beb838ec4e40"
os = "windows"

    [[ATK.download]]
    sha256 = "7a4e43d971a8ae95e90f3987a8c76e8406756549f2f8add948aaa067d708631d"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+4/ATK.v2.34.1.x86_64-w64-mingw32.tar.gz"
