[[ATK]]
arch = "aarch64"
git-tree-sha1 = "9165dc1c36d9e6a6d061675ac82f85b25eb4cd22"
os = "macos"

    [[ATK.download]]
    sha256 = "26b68295f2c10ce996964dd039732d6addd08efef22f4d2cc82ca82183235ab6"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.38.0+0/ATK.v2.38.0.aarch64-apple-darwin.tar.gz"
[[ATK]]
arch = "aarch64"
git-tree-sha1 = "c154aa1d5f79b776fe85d7e8334c11a1e831c3bb"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "01c95ca4e46d0f4080d321484dd3cc7e660635fbd0ac63829c30b6082d2b08bf"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.38.0+0/ATK.v2.38.0.aarch64-linux-gnu.tar.gz"
[[ATK]]
arch = "aarch64"
git-tree-sha1 = "6db2246cde9befbbf78fd5d13d1c305d746487d3"
libc = "musl"
os = "linux"

    [[ATK.download]]
    sha256 = "ea78d669c67a55054b6470a3656b1b3d1f5edf584d0196b7f2e1d9d6fa1274f5"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.38.0+0/ATK.v2.38.0.aarch64-linux-musl.tar.gz"
[[ATK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2991696b5846824b806fd5eb8d264b8389ead307"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "af7a9561cfb0819c461093e7eb63b9d52513b03eea3f3190e79b35d5ddc20398"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.38.0+0/ATK.v2.38.0.armv6l-linux-gnueabihf.tar.gz"
[[ATK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a6ed1e99fc43651ff2956ef1e2ab70d38ab419b7"
libc = "musl"
os = "linux"

    [[ATK.download]]
    sha256 = "562da92a878d9a02eae652124f4e94cf74305c575d13634c9408e684a6783513"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.38.0+0/ATK.v2.38.0.armv6l-linux-musleabihf.tar.gz"
[[ATK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0230ef888c0ae80dd4694d4e8a2de2adbb9d50ca"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "0020910709bbaf3d483cf277b1e7c3f6694ff01d447e186a665c101f3e68f069"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.38.0+0/ATK.v2.38.0.armv7l-linux-gnueabihf.tar.gz"
[[ATK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e68e227b068ac08acc4e4e68cf4fe186335e39bf"
libc = "musl"
os = "linux"

    [[ATK.download]]
    sha256 = "3ad130132364d119e46c30018c93695c7cb324191d236edf10fc16dc37fb499d"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.38.0+0/ATK.v2.38.0.armv7l-linux-musleabihf.tar.gz"
[[ATK]]
arch = "i686"
git-tree-sha1 = "bbebafec4ca638977b66d2db8763047b1ad59435"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "8075117ca6538b6c1bf444a92a49c95f989566c9eaa415e9c60d339f5d69a752"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.38.0+0/ATK.v2.38.0.i686-linux-gnu.tar.gz"
[[ATK]]
arch = "i686"
git-tree-sha1 = "62e71d7a0dcde09fac2d6aa75f434568a35ced7f"
libc = "musl"
os = "linux"

    [[ATK.download]]
    sha256 = "bc69813edf79abea18df6d3b5814c3a36f56672bbd5796cbe402250779af3c9c"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.38.0+0/ATK.v2.38.0.i686-linux-musl.tar.gz"
[[ATK]]
arch = "i686"
git-tree-sha1 = "f34cf1cb25ef03785629c5679c53a71309130bcc"
os = "windows"

    [[ATK.download]]
    sha256 = "8c74956157a53a7f8d48bec55f4dbdb670f3a2f1aaea0811f26573f3c056d33a"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.38.0+0/ATK.v2.38.0.i686-w64-mingw32.tar.gz"
[[ATK]]
arch = "powerpc64le"
git-tree-sha1 = "7294f7e9dc995fc8b35284ddf8ba781fac8b4c59"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "e3a34e49354cf82f8e6bb03d1e8fffe4c62ef5548751b3c78e567033750bd10b"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.38.0+0/ATK.v2.38.0.powerpc64le-linux-gnu.tar.gz"
[[ATK]]
arch = "x86_64"
git-tree-sha1 = "3d8e3c3a58f331b88f90baebe2dbe6a042465e3a"
os = "macos"

    [[ATK.download]]
    sha256 = "ad396ca946bdbfd7eeaa08416b55c69aefb73cbc8066f071e8c7eb02d2ad4d8e"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.38.0+0/ATK.v2.38.0.x86_64-apple-darwin.tar.gz"
[[ATK]]
arch = "x86_64"
git-tree-sha1 = "a42a6d314e2512dfaabbc3a1e483b0aa31a2c9ee"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "d00d05a3e1a0c2b04a865fcd73d7abb4e175efc281f8de67f86ef4373d42108a"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.38.0+0/ATK.v2.38.0.x86_64-linux-gnu.tar.gz"
[[ATK]]
arch = "x86_64"
git-tree-sha1 = "31828a562b1c7fe4c583cdd8a28c7a8c890bf516"
libc = "musl"
os = "linux"

    [[ATK.download]]
    sha256 = "47f88c6efeeae02f96c221f51979d5f615a27f49720df8bc93dcf4ee277a600c"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.38.0+0/ATK.v2.38.0.x86_64-linux-musl.tar.gz"
[[ATK]]
arch = "x86_64"
git-tree-sha1 = "d6a25e7d83030541a2b42befe0380151792e7089"
os = "freebsd"

    [[ATK.download]]
    sha256 = "c6400f4ef01b5d0fb835ff9d08b0610c35958801cad722efa9e94a68fdb53c1b"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.38.0+0/ATK.v2.38.0.x86_64-unknown-freebsd.tar.gz"
[[ATK]]
arch = "x86_64"
git-tree-sha1 = "e57abe973e31c68536d28ca676200a9a1219225c"
os = "windows"

    [[ATK.download]]
    sha256 = "2394eb934c66d47ec04c4fb8b7bc561d66171a17a954771ce20eaf3915709b41"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.38.0+0/ATK.v2.38.0.x86_64-w64-mingw32.tar.gz"
