[[ATK]]
arch = "x86_64"
git-tree-sha1 = "fe1051d30ab98f410eee02d32f096e30bc55dea4"
os = "macos"

    [[ATK.download]]
    sha256 = "e3f0de561b6f7f4dd6fc910db7adf7a5901ace91bd1de4a0ef735984d1e6c5b8"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+2/ATK.v2.34.1.x86_64-apple-darwin14.tar.gz"
[[ATK]]
arch = "powerpc64le"
git-tree-sha1 = "600e572b6112eda4930af82e1c0abb0457aabece"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "5fe8b436f62edfa19ead984d7bb08d871ab0378b332f58b0b6c687d78a9d8042"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+2/ATK.v2.34.1.powerpc64le-linux-gnu.tar.gz"
[[ATK]]
arch = "aarch64"
git-tree-sha1 = "cfaf706cef963c7eea0dcf8ad12e2a19b3b1f2b7"
libc = "musl"
os = "linux"

    [[ATK.download]]
    sha256 = "45019590434b372bfa9b1995cad6889ed7b7ef1e036badeafe0cc0860773d1ef"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+2/ATK.v2.34.1.aarch64-linux-musl.tar.gz"
[[ATK]]
arch = "x86_64"
git-tree-sha1 = "98906d9396c818c07665d68de5f1cb1070a067c5"
os = "freebsd"

    [[ATK.download]]
    sha256 = "07290a085a773ad58783842f01527c85033a9d56c7d4b67c09fba000b555ea72"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+2/ATK.v2.34.1.x86_64-unknown-freebsd11.1.tar.gz"
[[ATK]]
arch = "i686"
git-tree-sha1 = "3587c8a7c6be85e36a8d25bdea9349c2a7d17be0"
libc = "musl"
os = "linux"

    [[ATK.download]]
    sha256 = "56ba89ece7a8cc103a940d30ceeed39bf9dd5ecd284b36c76c6a71b7c8569611"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+2/ATK.v2.34.1.i686-linux-musl.tar.gz"
[[ATK]]
arch = "armv7l"
git-tree-sha1 = "c9b0c77b82797d8b66d99c37a84d16b106797661"
libc = "musl"
os = "linux"

    [[ATK.download]]
    sha256 = "1f8eea8e22e6b8df6a3b4bb80f478ec1ebdeb07bed042358f53ec861d99b5d38"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+2/ATK.v2.34.1.arm-linux-musleabihf.tar.gz"
[[ATK]]
arch = "i686"
git-tree-sha1 = "e8ed5bce17255a2c966415347b5c1f80d0c1156d"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "dc45b276cb048392eb17026484f65a63a8685e2631060c64b9dc7a4cbcc287ad"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+2/ATK.v2.34.1.i686-linux-gnu.tar.gz"
[[ATK]]
arch = "i686"
git-tree-sha1 = "cf1b6f0135b529637c11342d1f0e1f21d68fdab3"
os = "windows"

    [[ATK.download]]
    sha256 = "0d661afc8ec4cc1912d22f02f5eb9ef8d3d0f62f0819e6fdcc7cc0c591f66b8c"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+2/ATK.v2.34.1.i686-w64-mingw32.tar.gz"
[[ATK]]
arch = "x86_64"
git-tree-sha1 = "4c8e453bba07b6543b55b36db8d9656e51ba989d"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "31cc5bb116dcb8f9d68dcfd63c455e5a35cc410e50ea33e293dfadb4401bd814"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+2/ATK.v2.34.1.x86_64-linux-gnu.tar.gz"
[[ATK]]
arch = "x86_64"
git-tree-sha1 = "f1b2334614e57030e4aca2a3a0fb4ae3df3c8153"
os = "windows"

    [[ATK.download]]
    sha256 = "322b8ac9965534e25f8fbd6a7562f236f3bdffbf0423937fdc5349263f5fb350"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+2/ATK.v2.34.1.x86_64-w64-mingw32.tar.gz"
[[ATK]]
arch = "armv7l"
git-tree-sha1 = "1930a9ae71f37ed3a22f46a9fbcf8900ba5b4519"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "322d2ebe9a5d11af9794101668a5482dc5d10ae1fb63c6dc72297172ee89d6b5"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+2/ATK.v2.34.1.arm-linux-gnueabihf.tar.gz"
[[ATK]]
arch = "x86_64"
git-tree-sha1 = "9c9f959354371b6042fa18413041fab67f64502f"
libc = "musl"
os = "linux"

    [[ATK.download]]
    sha256 = "eed6aa0f69e8b05f9a5452140cde9dd4d59d3f1a6267cc460b26797b44377e9b"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+2/ATK.v2.34.1.x86_64-linux-musl.tar.gz"
[[ATK]]
arch = "aarch64"
git-tree-sha1 = "3695fbb469b222df4c61ec4f2bb472ca70cbf7b7"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "c61bf0b55a69b2106e373cf19038b2fce9e06ff6ab419397b09247e8a967f441"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+2/ATK.v2.34.1.aarch64-linux-gnu.tar.gz"
